---
- name: Apply base configuration to all Ubuntu servers
  hosts: all
  become: true
  roles:
    - role: unattended_upgrades
      vars:
        # 기본값을 덮어쓰고 싶을 때만 변수를 정의
        unattended_mail_to: "admin@example.com"
        unattended_reboot_time: "04:00"
      when: ansible_os_family == "Debian" # Debian 계열에서만 실행
