---
# tasks file for unattended_upgrades
- name: Install unattended-upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Configure main settings for unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Configure activation settings for unattended-upgrades
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
