---
- name: Add only admin users to the 'wheel' group
  hosts: all
  become: true
  vars:
    users:
      - name: alice
        is_admin: true
      - name: bob
        is_admin: false
  tasks:
    - name: Add user to wheel group
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: sudo
        append: yes
      loop: "{{ users }}"
      when: item.is_admin # item의 is_admin 값이 true일 때만 실행
