---
- name: DNS Master & Slave Server Configuration
  hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars/commons.yml
    - vars/local.yml
  tasks:
    - name: named.conf.options Jinja2 template
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: 0640
    - name: named.conf.local Jinja2 template
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: 0640

