---
- name: Update /etc/hosts on all nodes
  hosts: all
  become: true  # 작업을 root 권한(sudo)으로 실행합니다.

  tasks:
    - name: Add lab nodes to /etc/hosts
      blockinfile:
        path: /etc/hosts  # 수정할 파일 경로
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR LAB" # 관리 블록 표시자#description
        block: |
          10.10.8.3 server
          10.10.8.4 node1
          10.10.8.5 node2
          10.10.8.6 node3
          10.10.8.7 node4
