---
- hosts: web_servers
  become: true
  vars_files:
    - password.yml
    # --- 변수 설정 ---

      #    db_name: "wordpress"
      #    db_user: "wordpress_user"
      #    db_password: "P@ssw0rd"
      #    db_address: "10.10.8.5"
  vars:
    wordpress_path: /var/www/wordpress
    wordpress_domain: "{{ ansible_host }}"
    php_version: "8.3"
  tasks:
    # --- MariaDB, PHP, Nginx 패키지 일괄 설치 ---
    # 분할작업 후>
    - name: Install all required packages
      ansible.builtin.apt:
        name:
          - nginx
          - php-fpm
          - php-mysql
          - php-gd
        state: present
        update_cache: yes


    # --- PHP 설정 ---
    - name: Ensure php-fpm service is started and enabled
      ansible.builtin.service:
        name: php8.3-fpm # Ubuntu 24.04 기준
        state: started
        enabled: yes

    # --- WordPress 설치 ---
    - name: Get WordPress security salts
      ansible.builtin.uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: yes
      register: wordpress_salts

    - name: Create WordPress document root
      ansible.builtin.file:
        path: "{{ wordpress_path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create wp-config.php from template
      ansible.builtin.template:
        src: templates/wp-config.php.j2
        dest: "{{ wordpress_path }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: '0640'

    # Download and unpack latest WordPress
    - name: Download and unpack latest WordPress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "{{ wordpress_path }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: www-data
        group: www-data

    # --- Nginx 설정 ---
    - name: Create Nginx virtual host for WordPress
      ansible.builtin.template:
        dest: /etc/nginx/sites-available/wordpress
        src: templates/wordpress.conf.j2
      notify: Restart Nginx

    - name: Enable the new virtual host
      ansible.builtin.file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
      notify: Restart Nginx

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
