---
- name: Cleanup all
  hosts: webservers
  become: true
  vars:
    package_name: apache2
    service_name: apache2
  tasks:
    - name: Install the {{ package_name }} package
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: absent

    - name: Start and enable the {{ service_name }} service
      ansible.builtin.service:
        name: "{{ service_name }}"
        enabled: false
        state: stopped
