- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Purge Apache2 if it is installed
  ansible.builtin.apt:
    name: apache2
    state: absent
    purge: yes   # 설정 파일까지 모두 삭제
    autoremove: yes  # 의존성 패키지 자동 삭제
      #    when:
      #    - "'apache2' in ansible_facts.packages"

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

  #- name: DEBUG print ansible_facts
  #  debug:
  #var: ansible_facts.packages
