---
- name: FireWall setting Allow UFW
  hosts: all
  gather_facts: no
  become: true
  vars:
    firewall_rules: 
      - { rule: 'allow', port: '53', proto: 'tcp'}
      - { rule: 'allow', port: '53', proto: 'udp'}
      - { rule: 'allow', port: '22', proto: 'tcp'}

  tasks:
    - name: Apply firewall rules from list
      community.general.ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: "{{ firewall_rules }}"
    - name: Enable UFW
      community.general.ufw:
        state: enabled


